services:
  web:
    build: .
    container_name: node_container
    image: node_image
    volumes:
      - .:/code
    networks:
      - mynetwork
    ports:
      - "1111:1111"
networks: 
  mynetwork:
